spring.application.name=chachakim
server.port=4000

# 09월 04일에 관호가 _이걸 -이거로 바꿈
spring.mvc.pathmatch.matching-strategy=ant-path-matcher 


#Hibernate 설정에서 사용할 데이터베이스 방언을 명시적으로 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://chachakim.cvw8mo2gorqp.ap-northeast-2.rds.amazonaws.com:3306/chachakim?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=chachakim
spring.datasource.password=chachakim!!

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB



#임시로 순환 참조 가능 해놓음 나중에 없애고 순환 참조 구조를 바꿔야할듯
# spring.main.allow-circular-references=true


# 정적 리소스 경로 설정을 웹 URL의 컨텍스트 경로로 지정
spring.web.resources.static-locations=file:///C:/chachakim/chachakim-backend/uploads/
spring.web.resources.add-mappings=true

# jwt 토큰 설정
jwt.secret=2B7E151628AED2A6ABF7158809CF4F3C2B7E151628AED2A6ABF7158809CF4F3C
# jwt.expiration=3600000
#1시간 밀리초 단위

logging.level.org.apache.jasper=DEBUG



